from sqlalchemy import Column, Integer, String, DateTime, Text
from app.database import Base


class SLARecord(Base):
    __tablename__ = "sla_records"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    nomor_registrasi = Column(String(255), nullable=True, index=True)
    nama_dokumen = Column(Text, nullable=True)
    unit = Column(String(255), nullable=True, index=True)
    sumber = Column(String(100), nullable=True)
    status_registrasi = Column(String(500), nullable=True)
    status_inisiasi = Column(String(255), nullable=True)
    posisi_data = Column(String(255), nullable=True)
    format_arsip = Column(String(100), nullable=True)
    document_type = Column(String(100), nullable=True, index=True)

    tanggal_registrasi_raw = Column(String(80), nullable=True)
    jam_registrasi_raw = Column(String(80), nullable=True)
    tanggal_verifikasi_uf_raw = Column(String(80), nullable=True)
    jam_verifikasi_uf_raw = Column(String(80), nullable=True)
    tanggal_verifikasi_uu_raw = Column(String(80), nullable=True)
    jam_verifikasi_uu_raw = Column(String(80), nullable=True)
    tanggal_verifikasi_arsip_raw = Column(String(80), nullable=True)
    jam_verifikasi_arsip_raw = Column(String(80), nullable=True)
    tanggal_registrasi_2_raw = Column(String(80), nullable=True)
    jam_registrasi_2_raw = Column(String(80), nullable=True)
    tanggal_verifikasi_arsip_2_raw = Column(String(80), nullable=True)
    jam_verifikasi_arsip_2_raw = Column(String(80), nullable=True)
    tanggal_penjadwalan_inaktif_raw = Column(String(80), nullable=True)
    jam_penjadwalan_inaktif_raw = Column(String(80), nullable=True)
    tanggal_penolakan_jadwal_penjemputan_raw = Column(String(80), nullable=True)
    jam_penolakan_jadwal_penjemputan_raw = Column(String(80), nullable=True)
    tanggal_gagal_penjemputan_raw = Column(String(80), nullable=True)
    jam_gagal_penjemputan_raw = Column(String(80), nullable=True)
    tanggal_jadwal_penjemputan_raw = Column(String(80), nullable=True)
    jam_jadwal_penjemputan_raw = Column(String(80), nullable=True)
    tanggal_penjemputan_dokumen_raw = Column(String(80), nullable=True)
    jam_penjemputan_dokumen_raw = Column(String(80), nullable=True)
    tanggal_penjadwalan_inaktif_2_raw = Column(String(80), nullable=True)
    jam_penjadwalan_inaktif_2_raw = Column(String(80), nullable=True)

    registration_timestamp = Column(DateTime, nullable=True, index=True)
    verification_uf_timestamp = Column(DateTime, nullable=True)
    verification_uu_timestamp = Column(DateTime, nullable=True)
    verification_timestamp = Column(DateTime, nullable=True)
    registration_2_timestamp = Column(DateTime, nullable=True)
    verification_2_timestamp = Column(DateTime, nullable=True)

    sla_code = Column(String(20), default="SLA 1", nullable=False, index=True)
    status = Column(String(50), nullable=False, index=True)
    incomplete_reason = Column(Text, nullable=True)
    is_denominator = Column(Integer, default=1, nullable=False)

    sla1a_result = Column(String(10), nullable=True)
    sla1b_result = Column(String(10), nullable=True)
    sla1_decision_source = Column(String(80), nullable=True)
    sla1_manual_rule = Column(String(120), nullable=True)
    sla1_working_days = Column(Integer, nullable=True)
    sla2a_result = Column(String(10), nullable=True)
    sla2b_result = Column(String(10), nullable=True)
    sla2_final_result = Column(String(10), nullable=True)
    sla2_manual_result = Column(String(10), nullable=True)
    sla2_decision_source = Column(String(80), nullable=True)
    sla2_manual_rule = Column(String(120), nullable=True)
    sla2_working_days = Column(Integer, nullable=True)
    sla2a_working_days = Column(Integer, nullable=True)
    sla2b_working_days = Column(Integer, nullable=True)
    sla2_flow_stage = Column(String(80), nullable=True)
    sla2_reason = Column(Text, nullable=True)

    # SLA 3: primary/fallback formula results and manual fallback audit
    sla3a_result = Column(String(10), nullable=True)
    sla3b_result = Column(String(10), nullable=True)
    sla3_final_result = Column(String(10), nullable=True)
    sla3_manual_result = Column(String(10), nullable=True)
    sla3_decision_source = Column(String(80), nullable=True)
    sla3_manual_rule = Column(String(120), nullable=True)
    sla3_working_days = Column(Integer, nullable=True)
    sla3a_working_days = Column(Integer, nullable=True)
    sla3b_working_days = Column(Integer, nullable=True)
    sla3_flow_stage = Column(String(80), nullable=True)
    sla3_reason = Column(Text, nullable=True)
    holiday_calendar_version = Column(String(80), nullable=True)
    flow_stage = Column(String(80), nullable=True)
    reporting_period = Column(String(20), nullable=True)
